package com.upscaler.ai.ui

import java.util.Locale

/** Tiny bilingual string table (Arabic / English), picked from device locale. */
object S {
    val ar: Boolean get() = Locale.getDefault().language == "ar"
    private fun t(a: String, e: String) = if (ar) a else e

    val title get() = t("محسّن الفيديو AI", "Video Upscaler AI")
    val subtitle get() = t("من 144p إلى 4K بالذكاء الاصطناعي — على جهازك، بدون إنترنت", "144p → 4K with on-device AI. No internet needed")
    val pickVideo get() = t("اختر فيديو", "Pick a video")
    val changeVideo get() = t("تغيير الفيديو", "Change video")
    val start get() = t("ابدأ التحسين", "Start upscaling")
    val cancel get() = t("إلغاء", "Cancel")
    val model get() = t("موديل الذكاء الاصطناعي", "AI model")
    val preset get() = t("الجودة والسرعة", "Quality & speed")
    val target get() = t("الدقة المطلوبة", "Target resolution")
    val sharpen get() = t("حدّة إضافية", "Extra sharpness")
    val antiFlicker get() = t("منع الوميض (ثبات زمني)", "Anti-flicker (temporal stability)")
    val hevc get() = t("ترميز HEVC (حجم أصغر)", "HEVC encoding (smaller file)")
    val gpu get() = t("تسريع GPU/NPU", "GPU/NPU acceleration")
    val advanced get() = t("إعدادات متقدمة", "Advanced")
    val estimate get() = t("الوقت المتوقع", "Estimated time")
    val inputInfo get() = t("الفيديو الأصلي", "Source video")
    val output get() = t("النتيجة", "Output")
    val preparing get() = t("جارٍ التحضير…", "Preparing…")
    val processing get() = t("جارٍ المعالجة", "Processing")
    val frames get() = t("فريم", "frames")
    val skipped get() = t("فريمات مكررة تم توفيرها", "duplicate frames saved")
    val speed get() = t("السرعة", "Speed")
    val eta get() = t("الوقت المتبقي", "Remaining")
    val elapsed get() = t("الوقت المنقضي", "Elapsed")
    val engine get() = t("المحرك", "Engine")
    val done get() = t("تم بنجاح", "Done")
    val savedTo get() = t("تم الحفظ في: Movies/VideoUpscalerAI", "Saved to Movies/VideoUpscalerAI")
    val open get() = t("فتح", "Open")
    val share get() = t("مشاركة", "Share")
    val newVideo get() = t("فيديو جديد", "New video")
    val failed get() = t("حدث خطأ", "Failed")
    val retry get() = t("حاول مرة أخرى", "Try again")
    val cancelled get() = t("تم الإلغاء", "Cancelled")
    val screenOffOk get() = t("يمكنك قفل الشاشة — المعالجة تستمر في الخلفية", "You can lock the screen — processing continues in background")
    val keepPlugged get() = t("نصيحة: وصّل الشاحن لأفضل أداء", "Tip: plug in the charger for best performance")
    val tooLong get() = t("تحذير: الوقت المتوقع طويل. اختر إعداد أسرع أو دقة أقل.", "Warning: long estimated time. Pick a faster preset or lower resolution.")
    val permissionNeeded get() = t("نحتاج إذن الإشعارات لعرض التقدم", "Notification permission is needed to show progress")
    val duration get() = t("المدة", "Duration")
    val minutesShort get() = t("د", "m")
    val secondsShort get() = t("ث", "s")
    val hoursShort get() = t("س", "h")
    // v1.1
    val addVideos get() = t("إضافة فيديوهات", "Add videos")
    val videosSelected get() = t("فيديو محدد", "videos selected")
    val previewBtn get() = t("معاينة قبل/بعد + قياس سرعة الجهاز", "Preview before/after + benchmark device")
    val previewTitle get() = t("معاينة", "Preview")
    val before get() = t("قبل", "Before")
    val after get() = t("بعد (AI ×4)", "After (AI ×4)")
    val measuring get() = t("جارٍ قياس سرعة الجهاز…", "Benchmarking your device…")
    val measured get() = t("تقدير مقاس على جهازك", "Measured on your device")
    val estimatedRough get() = t("تقدير تقريبي — اضغط معاينة لقياس دقيق", "Rough estimate — tap Preview for accurate timing")
    val trim get() = t("قص الفيديو", "Trim")
    val trimHint get() = t("عالج جزء بس من الفيديو (اختياري)", "Process only a part of the video (optional)")
    val from get() = t("من", "From")
    val to get() = t("إلى", "To")
    val quickTest get() = t("اختبار سريع 10 ثواني", "Quick 10s test")
    val quickTestHint get() = t("جرّب الإعدادات على 10 ثواني قبل الفيديو الكامل", "Try your settings on 10 seconds before the full video")
    val startAll get() = t("ابدأ الكل", "Start all")
    val queueTitle get() = t("قائمة الانتظار", "Queue")
    val waiting get() = t("في الانتظار", "Waiting")
    val running get() = t("جارٍ", "Running")
    val cancelAll get() = t("إلغاء الكل", "Cancel all")
    val remove get() = t("إزالة", "Remove")
    val history get() = t("السجل", "History")
    val historyEmpty get() = t("لا توجد نتائج سابقة", "No previous results")
    val clearHistory get() = t("مسح السجل", "Clear history")
    val back get() = t("رجوع", "Back")
    val thermalNote get() = t("التطبيق يبرّد الجهاز تلقائياً لو سخن", "The app auto-pauses if the phone overheats")
    val allDone get() = t("اكتملت كل الفيديوهات", "All videos done")
    val perVideo get() = t("لكل فيديو", "per video")
    // v1.2
    val autoDetect get() = t("اكتشاف تلقائي", "Auto-detect")
    val autoModelOn get() = t("اختيار الموديل تلقائياً", "Pick model automatically")
    val colorMode get() = t("تحسين الألوان (GPU)", "Colour enhancement (GPU)")
    val colorSuggested get() = t("الفيديو باهت/غامق — نقترح تحسين الألوان", "Video looks washed-out/dark — colour fix suggested")
    val downloadModel get() = t("تحميل", "Download")
    val downloading get() = t("جارٍ التحميل", "Downloading")
    val deleteModel get() = t("حذف الموديل", "Delete model")
    val notDownloaded get() = t("غير محمَّل", "Not downloaded")
    val pause get() = t("إيقاف مؤقت", "Pause")
    val resumeBtn get() = t("استكمال", "Resume")
    val pausedLabel get() = t("متوقف مؤقتاً", "Paused")
    val compareHint get() = t("اسحب للمقارنة", "Drag to compare")
    // v1.3 cloud
    val compute get() = t("مكان المعالجة", "Where to process")
    val cloudOnline get() = t("GPU سحابي متاح", "Cloud GPU online")
    val cloudOffline get() = t("GPU سحابي غير متاح الآن — هيشتغل على الجهاز", "Cloud GPU offline — will run on device")
    val cloudFrames get() = t("فريمات من السحابة", "cloud frames")
    val cloudNote get() = t("السحابة مجانية (HuggingFace ZeroGPU / Kaggle). لتسريع أكبر شغّل نوتبوك Kaggle من الريبو.", "Cloud is free (HuggingFace ZeroGPU / Kaggle). For max speed run the Kaggle notebook from the repo.")
    val maxMode get() = t("أقصى دقة ممكنة — نفس الفيديو", "Maximum resolution — same video")
    val maxModeHint get() = t("الوضع التلقائي: اديني الفيديو واضغط ابدأ. الناتج هو نفس الفيديو بنفس الألوان والإضاءة بس بأعلى دقة يقدر يوصلها الموبايل (حتى 4K).", "Auto mode: pick a video and press Start. The result is the same video, same colours and brightness, at the highest resolution your phone can produce (up to 4K).")
    val expert get() = t("إعدادات يدوية (للخبراء)", "Manual settings (expert)")
    val willProduce get() = t("هيتحوّل إلى", "Will be upscaled to")
    val natural get() = t("مطابقة الأصل (ضد البلاستيك)", "Faithful to source (anti-plastic)")
    val naturalHint get() = t("0 = AI خام (ألوان وإضاءة متغيرة) • 100 = مطابق للأصل: نفس الألوان والإضاءة، تفاصيل أحدّ فقط", "0 = raw AI (shifted colours/brightness) • 100 = faithful: same colours & brightness, only sharper detail")
    val howItWorks get() = t("كيف يعمل؟", "How it works")
    val howItWorksBody get() = t(
        "1) يفك الفيديو بالهاردوير\n2) شبكة Real-ESRGAN تكبّر كل فريم ×4 على GPU/NPU\n3) يتخطى الفريمات المكررة ويثبّت النتيجة زمنياً\n4) يعيد الترميز HEVC مع نسخ الصوت الأصلي بدون فقدان",
        "1) Hardware decode\n2) Real-ESRGAN upscales each frame ×4 on GPU/NPU\n3) Skips duplicate frames & stabilizes temporally\n4) HEVC re-encode with lossless audio copy"
    )
}
